Add feature to enable upload of files to the rest api.
EdinburghGenomics/EGCG-Core pull request #49
Opened 2017-05-05 12:07 UTC by tcezard

This PR adds ability to upload file through POST PATCH or PUT via rest_communication.
it expect to have the file name in the json and will detect the file and upload it using request multipart form.
the usage would be:
```python
json_list = [
    {'element_id': 'e1', 'report_r1': ('file', 'path/to/file/to/upload1.html'},
    {'element_id': 'e2', 'report_r1': ('file', 'path/to/file/to/upload2.html'},
] 
rest_communication.post_or_patch('endpoint', json_list, 'element_id')
```

2017-05-05 12:37 UTC, katieemelianova approved these changes

2017-05-09 17:05 UTC, mwhamgenomics requested changes

2017-05-09 17:05 UTC, mwhamgenomics commented on egcg_core/rest_communication.py
> +    def _patch_entry(self, endpoint, doc, payload, update_lists=None, files_content=None):
`files_content` here is never used

2017-05-09 17:05 UTC, mwhamgenomics commented on egcg_core/rest_communication.py
> +        return None
If we return `None` here, could we end up trying to push `{'fastqc_report': null}` to the Rest API? If so, we should either make that nullable or return an empty list here instead.

2017-05-10 09:05 UTC, tcezard commented on egcg_core/rest_communication.py
> +        return None
No `_extract_files` returns a dict of files per `json_dict` provided.
The purpose of returning `None` explicitly here is to indicate that no files were found in the `json_dict`

```python
json_dict = {'key1': 'val1'}
print(_extract_files(json_dict))
>>> None
json_dict = {'key1': 'val1', 'key2': ('file', '/path/to/file.txt')}
print(_extract_files(json_dict))
>>> {'key2': ('/path/to/file.txt', 'filecontent', 'plain/text')}
```

2017-05-23 21:34 UTC, tcezard commented
I've added a test to check if we're uploading a nested json and files at the same time which raises an exception
Usage would be:
```python
#with simple json --> use only one query
json_list = [
    {'element_id': 'e1', 'key1': 'value1', 'report_r1': ('file', 'path/to/file/to/upload1.html')},
    {'element_id': 'e2', 'key1': 'value2', 'report_r1': ('file', 'path/to/file/to/upload2.html')},
] 
rest_communication.post_or_patch('endpoint', json_list, 'element_id')

#with nested json --> split in two queries
json_list = [
    {'element_id': 'e1', 'key1': {'k': 'v1'}},
    {'element_id': 'e2', 'key1': {'k': 'v2'}},
]
rest_communication.post_or_patch('endpoint', json_list, 'element_id')
json_list = [
    {'element_id': 'e1', 'report_r1': ('file', 'path/to/file/to/upload1.html')},
    {'element_id': 'e2', 'report_r1': ('file', 'path/to/file/to/upload2.html')},
]
rest_communication.post_or_patch('endpoint', json_list, 'element_id')
```
I tried to make `rest_communication` run the two queries but could not get it to work for function such as `post` or `put` because they do not receive `element_id` which is require for any subsequent patch.

2017-06-02 14:52 UTC, mwhamgenomics approved these changes

2017-06-05 11:34 UTC, merged