Add mapping stats and picard metrics
EdinburghGenomics/EGCG-Core pull request #62
Opened 2017-10-23 11:35 UTC by tcezard

Small PR to add new metric names
Also test that there are no duplicates in the constants

2017-10-25 09:22 UTC, mwhamgenomics requested changes

2017-10-25 09:22 UTC, mwhamgenomics commented on tests/test_constant.py
> +        uniq_constants.add(constant)
- The `assert True` below will have no effect during a test
- The `assert False` above could just be `assert constant not in uniq_constants`

2017-10-25 13:05 UTC, katieemelianova approved these changes
Approved pending Murray's requested changes

2017-10-30 13:50 UTC, mwhamgenomics requested changes

2017-10-30 13:50 UTC, mwhamgenomics commented on tests/test_constant.py
> +        assert constant not in uniq_constants
This will just assert that `constant` is not in an empty set, which will always be True!

2017-10-31 11:54 UTC, mwhamgenomics approved these changes

2017-10-31 13:31 UTC, merged